# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build

on: [push]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 genbadge[all] coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unittest
      run: |
        coverage run -m unittest
        python -m coverage report -m --skip-covered
        python -m coverage html -d .coverage_html
        python -m coverage xml -o .coverage.xml
        genbadge coverage --input-file .coverage.xml -o .coverage-badge.svg
        git config --global user.name 'AlexP210'
        git config --global user.email 'AlexP210@users.noreply.github.com'
        git add .coverage.xml .coverage-badge.svg
        git commit -m "Coverage Report"
        git push